basic.forever(function () {
    basic.showIcon(IconNames.No)
    pins.digitalWritePin(DigitalPin.P0, 1)
    basic.pause(3000)
    pins.digitalWritePin(DigitalPin.P0, 0)
    basic.pause(3000)
    pins.digitalWritePin(DigitalPin.P0, 1)
    basic.pause(3000)
    pins.digitalWritePin(DigitalPin.P0, 0)
    basic.pause(3000)
    pins.digitalWritePin(DigitalPin.P0, 1)
    basic.pause(3000)
    pins.digitalWritePin(DigitalPin.P0, 0)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(5000)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.clearScreen()
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.showNumber(5)
    basic.pause(3000)
    basic.showNumber(4)
    basic.pause(3000)
    basic.showNumber(3)
    basic.pause(3000)
    basic.showNumber(2)
    basic.pause(3000)
    basic.showNumber(1)
    pins.digitalWritePin(DigitalPin.P2, 1)
})
